// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPWnb1dK9EtqRT_KPRItb9mmNstjyBf6c',
    appId: '1:914732775639:web:3424af9e05b7d12e6e5892',
    messagingSenderId: '914732775639',
    projectId: 'esports-sync',
    authDomain: 'esports-sync.firebaseapp.com',
    storageBucket: 'esports-sync.firebasestorage.app',
    measurementId: 'G-8EL9CWE2TL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSnkwmT3aoKXARtpvLdRNSDrIZ_Jb0EbA',
    appId: '1:914732775639:android:9a81ec511e46306d6e5892',
    messagingSenderId: '914732775639',
    projectId: 'esports-sync',
    storageBucket: 'esports-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAti9GhME9NTeOZ8i0ejWIl2WzKc5-yKb0',
    appId: '1:914732775639:ios:8894faac41bb50236e5892',
    messagingSenderId: '914732775639',
    projectId: 'esports-sync',
    storageBucket: 'esports-sync.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAti9GhME9NTeOZ8i0ejWIl2WzKc5-yKb0',
    appId: '1:914732775639:ios:8894faac41bb50236e5892',
    messagingSenderId: '914732775639',
    projectId: 'esports-sync',
    storageBucket: 'esports-sync.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPWnb1dK9EtqRT_KPRItb9mmNstjyBf6c',
    appId: '1:914732775639:web:16fd87ed189df0476e5892',
    messagingSenderId: '914732775639',
    projectId: 'esports-sync',
    authDomain: 'esports-sync.firebaseapp.com',
    storageBucket: 'esports-sync.firebasestorage.app',
    measurementId: 'G-LD8GHXJEL1',
  );
}
